### ISSUE TITLE
error installing ezdxf

### ISSUE THREAD

**Issue by jmlg10** [tapnair/Export2D#2]
Hello, 

For any reason the ezDXF lidrary don't install properly and I can't try your Export2D add-in.

Is there any instruction to install it manually?
![image](https://user-images.githubusercontent.com/33903686/111678526-ae53f180-8820-11eb-9d71-f6f77f916e83.png)

**Comment by tapnair** [comment]
Ahh man thanks, I knew I should have actually tested that on Windows.  So complicated, but I think I'm pretty sure it's working now.  Down the latest build (don't clone the repo) and it should install correctly now on Windows.
If you had to install manually you would need to do this, but it assumes python and pip are installed on your machine and your path is configured right.  I have this is not often the case on most windows computers, which is why I have tried to build this auto-install of dependencies.
Open a command shell and navigate to the **lib** directory in the **Export2D** folder then execute:
`python -m pip install --target=. ezdxf[draw]`

**Comment by jmlg10** [comment]
Hi,

I'm really sorry but it don't works…

And the manual install neither.

I assume I have Python installed somewhere (at least a runtime), but I guess that it is not installed at a "system" level
So the command to install don't works…

***@***.***D71CA5.99787970]

Do you have any suggestion?

Many Thanks


Cordialement / Best Regards

Jean-Michel LE GOFF | Responsable Recherches Numériques | Louis Vuitton Malletier | 2, Rue du Pont-Neuf, 75001 Paris, France | Phone: +33 155803048 | Mobile : +33 664405492 | Email address:  ***@***.***

De : Patrick Rainsberry ***@***.***>
Envoyé : vendredi 19 mars 2021 03:33
À : tapnair/Export2D ***@***.***>
Cc : Jean-Michel LE GOFF ***@***.***>; Author ***@***.***>
Objet : Re: [tapnair/Export2D] error installing ezdxf (#2)

________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Ahh man thanks, I knew I should have actually tested that on Windows. So complicated, but I think I'm pretty sure it's working now. Down the latest build (don't clone the repo) and it should install correctly now on Windows.
If you had to install manually you would need to do this, but it assumes python and pip are installed on your machine and your path is configured right. I have this is not often the case on most windows computers, which is why I have tried to build this auto-install of dependencies.
Open a command shell and navigate to the lib directory in the Export2D folder then execute:
python -m pip install --target=. ezdxf[draw]

**Comment by jmlg10** [comment]
hi,
trying running the manual install I get this:
![image](https://user-images.githubusercontent.com/33903686/111755336-45f52680-8899-11eb-9ff9-e4d5d352dc59.png)

How I can run Python script from commend line?

**Comment by jmlg10** [comment]
I'm trying the manual install via iPy (IronPython) but "pip" command is not recocnized
![image](https://user-images.githubusercontent.com/33903686/111777022-ff142a80-88b2-11eb-8dee-d2e18161d007.png)

**Comment by jmlg10** [comment]
Hi,
for your information, I've succeded at last to install the ezDXF libs...(maually as I can't find how to use the --target=. option.

Anyway.

**Comment by tapnair** [comment]
Hello sorry for the trouble, I spent a ton of time trying to get this to work on Windows and thought I had it.  Can you share the error you are getting from the new download when it tries to do the install from within Fusion 360?

I have spent probably 10X longer trying to get this automatic installation to work as it took to make the add-in.  I really want to get that working because it always seems to be this very complicated process to get python and pip working on windows computers.  As you have experienced it seems.

**Comment by jmlg10** [comment]
Hello,

Thanks for your return.

I don’t know if I shall be able to help you troubleshooting the installation on Windows.

First, as I’m working in a corporate environment and it could be one issue by itself.
I have had to ask to unlock the Python 3.9 installer from Windows store to be able to go further.

Next I have had to update Pip

After, I tried to install ezdxf but it installs in another location than in the addin’s lib

Finally I copy/paste all it was installed in Python’s libs to the location you mentioned.

But on the other hand one issue may come from my need to install the addin from D:\ drive instead of C:\

Let me know if you need more informations.

On the other hand, thanks to you for your work, I’m trying several of your addins, and they can help to make Fusion 360 more usable for us.

I hope that it could be possible to implement some of them in the regular product
Export2d
Configsaver
Paramedit
FusionFiller
Etc...


Cordialement


Jean-Michel LE GOFF | Responsable Recherches Numériques | Louis Vuitton Malletier |+33664405492

Le 19 mars 2021 à 20:14, Patrick Rainsberry ***@***.***> a écrit :

﻿
________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Hello sorry for the trouble, I spent a ton of time trying to get this to work on Windows and thought I had it. Can you share the error you are getting from the new download when it tries to do the install from within Fusion 360?

I have spent probably 10X longer trying to get this automatic installation to work as it took to make the add-in. I really want to get that working because it always seems to be this very complicated process to get python and pip working on windows computers. As you have experienced it seems.

**Comment by tapnair** [comment]
Can you just send me a screen shot of the error you got in Fusion if any when you try to let the add-in install the libraries?

**Comment by jmlg10** [comment]
I shall try, but as it running now I’m not sure I shall be able.

I shall try to reinstall the add-in to see what happened.

Did you see my request about the unit in FusionFiller and the ability to use gyroid fill instead of hex,square,etc?

Many thanks


Cordialement


Jean-Michel LE GOFF | Responsable Recherches Numériques | Louis Vuitton Malletier |+33664405492

Le 19 mars 2021 à 20:42, Patrick Rainsberry ***@***.***> a écrit :

﻿
________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Can you just send me a screen shot of the error you got in Fusion if any when you try to let the add-in install the libraries?

**Comment by jmlg10** [comment]
When I try to install in the \lib
with this commend: pip install --target=. ezdxf[draw]
I get this.
ERROR: Can not combine '--user' and '--target'
have you any hint? I don't use '--user' !!😟

**Comment by jmlg10** [comment]
![Capture_export2D](https://user-images.githubusercontent.com/33903686/112615949-71d95480-8e23-11eb-9b3a-67267a37ba2c.PNG)
here is a screen capture when I launch the export

**Comment by jmlg10** [comment]
I tried to install without the --target option, and the module has been installed somewhere else...
![image](https://user-images.githubusercontent.com/33903686/112616662-4a36bc00-8e24-11eb-89b6-dda733d885e3.png)
